/**
 * Asset module declarations.
 *
 * Metro resolves a static image require at bundle time and hands the bundler a
 * numeric asset id, which React Native's `Image` accepts as a `source`. Nothing
 * in the type system knew that, so `import logo from './x.png'` failed with
 * TS2307 ("Cannot find module ... or its corresponding type declarations") even
 * though the runtime path was valid and jest-expo's asset transformer handled it
 * in tests. Only the compile-time half was missing.
 *
 * Typed as `ImageSourcePropType` rather than `number` because that is what
 * `Image` actually accepts, so a wrong-shaped source is still a type error.
 *
 * NOT `expo-env.d.ts` — that file is generated by `expo` and gitignored
 * (.gitignore:10), so a declaration added there would not survive a fresh
 * clone. Extend this block for other asset types as they are introduced.
 */
declare module '*.png' {
  import type { ImageSourcePropType } from 'react-native';

  const content: ImageSourcePropType;
  export default content;
}
