# Generated by Django 5.2.17 on 2026-09-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioclip',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/%Y/%m/%d/'),
        ),
    ]
