# Generated by Django 5.2.17 on 2026-09-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='audioclip',
            constraint=models.CheckConstraint(condition=models.Q(('likes__gte', 0)), name='likes_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='audioclip',
            constraint=models.CheckConstraint(condition=models.Q(('shares__gte', 0)), name='shares_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='audioclip',
            constraint=models.CheckConstraint(condition=models.Q(('skips__gte', 0)), name='skips_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='audioclip',
            constraint=models.CheckConstraint(condition=models.Q(('comment_count__gte', 0)), name='comment_count_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(('likes__gte', 0)), name='comment_likes_non_negative'),
        ),
    ]
