# Generated by Django 5.2.17 on 2026-09-03 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_audioclip_likes_non_negative_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='encrypted_email',
        ),
    ]
