# Generated by Django 5.2.17 on 2026-09-04 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_user_encrypted_email'),
    ]

    operations = [
        # DECISION: Remove Comment.likes field and its non-negative
        # constraint. The field had zero writers in the codebase; the
        # constraint protected an always-zero column. No data migration
        # needed because the field was never populated.
        migrations.RemoveConstraint(
            model_name='comment',
            name='comment_likes_non_negative',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
