# Generated by Django 5.2.17 on 2026-09-13 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_revenuecat_fields'),
        ('app', '0004_merge_revenue_and_segments'),
    ]

    operations = [
    ]
